version: '3'

services:
    selenium-hub:
        image: selenium/hub:3.141.59
        container_name: selenium-hub
        ports:
            - "4444:4444"

    chrome:
        image: selenium/node-chrome:3.141.59
        environment:
            - HUB_HOST=selenium-hub
            - NODE_MAX_INSTANCES=5

    firefox:
        image: selenium/node-firefox:3.141.59
        environment:
            - HUB_HOST=selenium-hub

    opera:
        image: selenium/node-opera:3.141.59
        environment:
            - HUB_HOST=selenium-hub
